<?php

/**
 * @file
 * Code for the schemax_location feature.
 */
include_once 'schemax_location.features.inc';

/**
 * Implements hook_form_alter().
 *
 * Add geofield feature layer to "Zoom to layer" behaviour
 */
function schemax_location_form_alter(&$form, &$form_state, $form_id) {
  // 'ctools_export_ui_edit_item_form' = openlayers map edit form (via ctools)
  if ($form_id == 'ctools_export_ui_edit_item_form') {
    // Check for geofield module presence
    if (module_exists('geofield')) {
      // Check if geofield behaviour is enabled (this form element will most likely be only in openlayers map edit form)
      if (drupal_array_get_nested_value($form, array('behaviors', 'openlayers_behavior_geofield', 'enabled', '#default_value'))) {
        // Check form has options that need to be altered
        if ($options = &drupal_array_get_nested_value($form, array('behaviors', 'openlayers_behavior_zoomtolayer', 'options_set', 'options', 'zoomtolayer', '#options'))) {
          // Append 'openlayers_behavior_geofield' layer to existing layers
          $options = array_merge($options, array('openlayers_behavior_geofield' => 'openlayers_behavior_geofield'));
        }
      }
    }
  }
}

/**
 * Implements hook_field_attach_form().
 */
function schemax_location_field_attach_form($entity_type, $entity, &$form, &$form_state, $langcode) {

  // Check if the form is a node edit form.
  if (!empty($form['#node_edit_form'])) {

    $bundle = $form['#bundle'];
    if ($bundle == 'schemax_location') {
      schemax_location_add_js();
    }
  }
}

/**
 * Implements MODULE_preprocess_HOOK().
 */
function schemax_location_preprocess_html(&$variables) {
  $path = drupal_get_path_alias();

  // Add custom js and css for paths starting with 'location'.
  if (strpos($path, 'location') === 0) {

    schemax_location_add_js();
    drupal_add_css(drupal_get_path('module', 'schemax_location') . '/css/schemax_location.css', array('group' => CSS_DEFAULT, 'weight' => 100));
  }
}

/**
 * Add js for map overlays
 */
function schemax_location_add_js() {

  drupal_add_js(drupal_get_path('module', 'schemax_location') . '/js/schemax_location.js', array('group' => JS_DEFAULT, 'weight' => 100));
}
